References
----------
.. [CIT1] \A. Dubey, A. Bose, M. Liu and L. N. Ochoa, "Paving the Way for Advanced Distribution Management Systems Applications: Making the Most of Models and Data," in *IEEE Power and Energy Magazine*, vol. 18, no. 1, pp. 63-75, Jan.-Feb. 2020
.. [CIT2] \S. Poudel, A. Dubey and K. P. Schneider, "A Generalized Framework for Service Restoration in a Resilient Power Distribution System," *Submitted to IEEE Systems Journal (Under Revision)*
.. [CIT3] \M. Venkateswara Reddy, and Anamika Dubay, ”Identification of Anomalous Voltage Measurements in Power Distribution Systems using Recursive PCA,” submitted in IEEE Transaction. (Under Review)
.. [CIT4] \M. Venkateswara Reddy and Anamika Dubay, ”Primary Voltage Forecasting in Distribution Systems using Principal Component Analysis”, 2021 IEEE Power \& Energy Society General Meeting (PESGM), Washington-DC, USA. (Accepted)
.. [CIT5] \A.  Imayakumar,  A.  Dubey,  and  A.  Bose,  “Anomaly  detection  for primary  distribution  system  measurements  using  principal  component analysis,” in2020 IEEE Texas Power \& Energy Conference (TPEC), pp. 1–6, 2020.
